### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by bryonpokemon** [cChimney/Discord-name-avatar-changer-and-scraper#2]
1. add bio scraper and changer
2. Instead of saving the link of pfp, download the pfp and save it to a folder
3. proxy support (regular and authenticated)
4. proxy scraper
5. random hype squad

**Comment by cChimney** [comment]
Will add bio scraper soon, saving the link saves more space on rdps n shit so did that. Proxy support is going to be added at 10 stars. Proxy scraper wont work that good as some proxies may be dead already so tokens wont change pfp. Random hypesquad gonna be added soon too
